package cmd

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

var makefileOutput string

var makefileCmd = &cobra.Command{
	Use:   "makefile",
	Short: "Generate Makefile targets for RTM commands",
	Long: `Output Makefile targets for common RTMX operations.

Examples:
    rtmx makefile                   # Print to stdout
    rtmx makefile -o rtmx.mk        # Write to file
    rtmx makefile >> Makefile       # Append to Makefile`,
	RunE: runMakefile,
}

func init() {
	makefileCmd.Flags().StringVarP(&makefileOutput, "output", "o", "", "output file (default: stdout)")

	rootCmd.AddCommand(makefileCmd)
}

func runMakefile(cmd *cobra.Command, args []string) error {
	content := generateMakefileContent()

	if makefileOutput != "" {
		if err := os.WriteFile(makefileOutput, []byte(content), 0644); err != nil {
			return fmt.Errorf("failed to write makefile: %w", err)
		}
		cmd.Printf("Written to %s\n", makefileOutput)
		return nil
	}

	cmd.Print(content)
	return nil
}

func generateMakefileContent() string {
	return `# RTMX Makefile Targets
# Generated by rtmx makefile

.PHONY: rtm backlog health deps cycles verify

# Show RTM status
rtm:
	@rtmx status

# Show prioritized backlog
backlog:
	@rtmx backlog

# Run health check
health:
	@rtmx health

# Show dependency graph
deps:
	@rtmx deps

# Check for cycles
cycles:
	@rtmx cycles

# Verify test coverage
verify:
	@rtmx verify

# Verify and update status
verify-update:
	@rtmx verify --update

# Show workable requirements
workable:
	@rtmx deps --workable

# Initialize new project
init:
	@rtmx init

# Reconcile dependencies
reconcile:
	@rtmx reconcile

# Reconcile and fix
reconcile-fix:
	@rtmx reconcile --execute

# Filter backlog by phase
backlog-phase:
	@rtmx backlog --phase $(PHASE)

# Show critical path
critical:
	@rtmx backlog --view critical

# Show quick wins
quick-wins:
	@rtmx backlog --view quick-wins
`
}
